### ISSUE TITLE
How do you do deploy and debug?

### ISSUE THREAD

**Issue by oshliaer** [eiel/babel-preset-google-apps-script#1]
Hi!
It's really cool stuff. Thanks.

Please, could you describe me how do you do deploy and debug gs projects?

**Comment by eiel** [comment]
Sorry.I'm beginner about google apps script.
I use [node-google-apps-script](https://github.com/danthareja/node-google-apps-script) after I did babel or rollup for deploy.
I still have trying various method.

**Comment by oshliaer** [comment]
@eiel It's my way too. Also you could look for other dev tools here https://github.com/oshliaer/google-apps-script-awesome-list#development
I'm using console.log for debug.

**Comment by eiel** [comment]
Thank you. I will try.
